using AFALXCourse.Lessons.M2.L2;
using ALX_Course.Assignments.M1;
using ALX_Course.Assignments.M2;
using ALX_Course.Lessons;
using ALX_Course.Lessons.M1.L1;
using ALX_Course.Lessons.M1.L2;
using ALX_Course.Lessons.M2.L1;
using ALX_Course.Lessons.M2.L2;
using System;

Console.Write("Michal Nycz\n");
Console.WriteLine("ALX Course");
Console.WriteLine("----------------------");

//L1ObjectVariables.Run2();
//L1ObjectVariables.WriteSth();
//L1SimpleVariables.Run();
//L1Strings.ConcatenationTest();
//L1Constructors.Run();
//AssignmentsDemo.Run();
//L2Conditionals.Run();
//L2EnumsAndSwitch.Run();
//SeniorityServiceTest.Run();
//L1Arrays.Run1();
//L1Arrays.Run2();
//L1Lists.Run();
//L1Loops.RunForeach();
//L1Loops.RunFor();
//L1Loops.RunWhile2();
//L1Dictionaries.Run1();
//L2GettersAndSetters.Run();
//L2Encapsulation.Run();
//L2Interfaces.Run();
L2Inheritance.Run();